services:
  api:
    build: ./api
    container_name: api
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - PRODUCTION=False
      - PERSISTENT_CONFIG_FILENAME="config.std"
    ports:
      - '${API_STD_PORT}:${API_STD_PORT}'
    volumes:
      - ./.env.local:/usr/src/.env:ro
      - /etc/localtime:/etc/localtime
      - api_mqtt_gateway_config:/usr/src/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`$(SUBDOMAIN_API)$(DOMAIN)`)"
      # - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=${API_STD_PORT}"
      # - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    networks:
      - backnet
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        uvicorn main:app --host "0.0.0.0" --port ${API_STD_PORT} --proxy-headers

  traefik:
    build:
      context: ./.traefik
      dockerfile: Dockerfile.dev
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.traefik/public-certificates:/certificates"
    command:
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL})"
      - "--providers.docker=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${SUBDOMAIN_TRAEFIK_DASH}${DOMAIN}`) && (PathPrefix(`/`))"
      - "traefik.http.routers.traefik.tls=false"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - backnet

networks:
  backnet:

volumes:
  api_mqtt_gateway_config:

